In [1]:
import numpy as np


In [2]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [3]:
B = np.array(range(1,4))
B

array([1, 2, 3])

In [4]:
C = np.ones([1,5])
C

array([[1., 1., 1., 1., 1.]])

In [5]:
CC = np.zeros([2,5])
CC

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
CC.shape

(2, 5)

In [7]:
A = np.array([1,2,3])
B = np.array([3,2,1])
#사칙연산
A+B

array([4, 4, 4])

In [8]:
A-B

array([-2,  0,  2])

In [9]:
A*B

array([3, 4, 3])

In [10]:
A/B

array([0.33333333, 1.        , 3.        ])

In [11]:
#npy파일로 저장
np.save("test1",A)

In [12]:
#파일 업로드
C = np.load("/content/test1.npy")
C

FileNotFoundError: [Errno 2] No such file or directory: '/content/test1.npy'

In [13]:
#csv파일로 저장
np.savetxt("test2.csv",A)

In [18]:
#csv파일 업로드
D = np.loadtxt("/content/test2.csv")
D

array([1., 2., 3.])

In [19]:
#첫줄 생략
data = np.loadtxt("/content/test2.csv",skiprows=1)
data

array([2., 3.])

In [20]:
E = data[1:3]
E

array([3.])

In [22]:
#평균
E = np.mean(data)
E

2.5

In [23]:
#분산
np.var(data)

0.25

In [24]:
#표준편차
np.std(data)

0.5

In [25]:
#1사분위 수
np.percentile(data, 25)

2.25

In [26]:
#3사분위 수
np.percentile(data, 75)

2.75

In [ ]:
8