In [2]:
import tensorflow as tf

tensor1 = tf.constant(3)
print(tensor1)

tf.Tensor(3, shape=(), dtype=int32)


In [3]:
tensor1

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [5]:
tensor1 = tf.constant([3,4,5])
tensor2 = tf.constant([6,7,8])
print(tensor1 + tensor2)

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)


In [6]:
print(tensor1 * tensor2)

tf.Tensor([18 28 40], shape=(3,), dtype=int32)


In [7]:
#제곱
print(tf.square(tensor1))

tf.Tensor([ 9 16 25], shape=(3,), dtype=int32)


tf.add()        합
tf.subtract()   빼기
tf.divide()     나누기
tf.multiply()   곱하기
tf.matmul()

In [9]:
print(tf.multiply(tensor1, tensor2))

tf.Tensor([18 28 40], shape=(3,), dtype=int32)


In [10]:
tensor3 = tf.constant([[1,2],[3,4]])
tensor4 = tf.constant([[5,6],[7,8]])
print(tf.matmul(tensor3, tensor4))

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [12]:
tensor5 = tf.zeros([2,2,3])
tensor6 = tf.ones([2,2])
print(tensor5, tensor6)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 2, 3), dtype=float32) tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [16]:
w = tf.Variable(1.0)
print(w)
print(w.numpy())

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>
1.0


In [19]:
w = tf.Variable(1.1)
w.assign(2.1)
print(w.numpy())

2.1
