In [2]:
import numpy as np

a = [1,2,3,4,5]

b = np.array(a)
c = np.array([1,3,5,7])
d = np.array([[1,2,3],[4,5,6]])

print(a)
print(b)
print(c)
print(d)


[1, 2, 3, 4, 5]
[1 2 3 4 5]
[1 3 5 7]
[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np

a = [1,2,3,4,5]
b = a
c = a.copy()

b[0] = 99

print(a,b,c)

[99, 2, 3, 4, 5] [99, 2, 3, 4, 5] [1, 2, 3, 4, 5]


In [11]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([1,3,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
e = np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]])
print(a[2])
print(b[-1])
print(a[1:3])
print(c[0])
print(d[0])
print(d[0][0])
print(d.strides)
print(e.strides)

3
5
[2 3]
[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 2 3]
(24, 12, 4)
(32, 16, 8, 4)


In [13]:
import numpy as np
n_arr = np.array([[1,2,3,4],[5,6,7,8]],dtype='int64')

print(n_arr)
print("type",type(n_arr))
print("dtype",n_arr.dtype)
print("ndim",n_arr.ndim)
print("shape",n_arr.shape)
print("size",n_arr.size)
print("itemsize",n_arr.itemsize)
print("nbytes",n_arr.nbytes)
print("data",n_arr.data)

print("메모리주소",id(n_arr))

[[1 2 3 4]
 [5 6 7 8]]
type <class 'numpy.ndarray'>
dtype int64
ndim 2
shape (2, 4)
size 8
itemsize 8
nbytes 64
data <memory at 0x000002099E12BD30>
메모리주소 2240329310224


In [26]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[3,2,1],[6,5,4]])
print(b + c)
print(b + 2)
print(b * 2)
print(b + [2,2,2])

print("---------------")
d = np.array([[1,2,3],[4,5,6]])

print(d + [3,6,9])

d = np.array([[1,2,3],[4,5,6]])

print(d * [3,6,9])

[[ 4  4  4]
 [10 10 10]]
[[3 4 5]
 [6 7 8]]
[[ 2  4  6]
 [ 8 10 12]]
[[3 4 5]
 [6 7 8]]
---------------
[[ 4  8 12]
 [ 7 11 15]]
[[ 3 12 27]
 [12 30 54]]


In [28]:
import numpy as np

a = np.array([1,2,3], dtype='float')
b = np.array([1,2,3], dtype='int')
c = np.array([1,0,1,0], dtype='bool')

print(a)
print(b)
print(c)
print(a.dtype)
print(b.dtype)
print(c.dtype)

[1. 2. 3.]
[1 2 3]
[ True False  True False]
float64
int32
bool


In [29]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print('a + b = ',a + b)
print('a - b = ',np.add(a,b))

print('a - b = ',a - b)
print('a - b = ',np.subtract(a,b))

print('a * b = ',a * b)
print('a * b = ',np.multiply(a,b))

print('a / b = ',a / b)
print('a / b = ',np.divide(a,b))

print('a // b = ',a // b)
print('a // b = ',np.floor_divide(a,b))

a + b =  [ 6  8 10 12]
a - b =  [ 6  8 10 12]
a - b =  [-4 -4 -4 -4]
a - b =  [-4 -4 -4 -4]
a * b =  [ 5 12 21 32]
a * b =  [ 5 12 21 32]
a / b =  [0.2        0.33333333 0.42857143 0.5       ]
a / b =  [0.2        0.33333333 0.42857143 0.5       ]
a // b =  [0 0 0 0]
a // b =  [0 0 0 0]


In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7])

print('a + b = ' ,a + b)
print('a + b = ' ,np.add(a,b))      #수가 맞지 않아 계산 불가능

In [31]:
a1 = np.arange(12)

print('a1 =',a1)
a2 = a1.reshape(3,4)
print('a2 =',a2)
a3 = a1.reshape(6,-1)
print('a3 =',a3)
a4 = np.arange(36, dtype = float).reshape(3,4,3)
print('a4 =',a4)

a1 = [ 0  1  2  3  4  5  6  7  8  9 10 11]
a2 = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a3 = [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
a4 = [[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]
  [ 9. 10. 11.]]

 [[12. 13. 14.]
  [15. 16. 17.]
  [18. 19. 20.]
  [21. 22. 23.]]

 [[24. 25. 26.]
  [27. 28. 29.]
  [30. 31. 32.]
  [33. 34. 35.]]]


In [33]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])

print(np.multiply(a1,a2))

print(np.matmul(a1,a2))

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [34]:
a = np.arange(12)
b = a.reshape(3,4)
print(a)
print(b)

b[0,0] = 11

print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[11  1  2  3  4  5  6  7  8  9 10 11]
[[11  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
