In [8]:
import numpy as np

a1 = np.arange(1,13)        # arange
a2 = a1.reshape(2,-1)
print(a2)

a3 = np.arange(1,31)
a4 = a3.reshape(3,-1)
print(a4)

a5 = a4.reshape(6,-1)
print(a5)

a6 = a5.transpose()         #전치행렬
print(a6)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]
 [ 5 10 15 20 25 30]]


In [13]:
a1 = np.array([1,2,3,4])            #비교
a2 = np.array([4,2,3,1])

print(a1 ==a2)
print(a1 < a2)

[False  True  True False]
[ True False False False]


In [15]:
a = np.array([5,1,3,2,5,1,6,7])

print(a)

print(np.sort(a))       #정렬
print(a)

a.sort()                #np 사용 안하고 정렬

print(a)

print(np.sort(a)[::-1])       #역순위로 정렬

[5 1 3 2 5 1 6 7]
[1 1 2 3 5 5 6 7]
[5 1 3 2 5 1 6 7]
[1 1 2 3 5 5 6 7]
[7 6 5 5 3 2 1 1]


In [37]:
a = np.arange(16).reshape(4,4)
print(a[:4,1])          #배열 자르기

print(a[2,1:4])

print(a[:2,:2])

print(a[1:3,1:3])

[ 1  5  9 13]
[ 9 10 11]
[[0 1]
 [4 5]]
[[ 5  6]
 [ 9 10]]
